### ISSUE TITLE
Formula style is broken.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [MicrosoftDocs/quantum-docs-pr.ja-JP#1]
A formula in the second paragraph has a broken formula. You should not modify the latest format during the translation.

Translated (wrong):
&gt; $ \ket{+} = \ left (\ket{0} + \ket{1}/\ sqrt{2}$

Original:
&gt; $\ket{+} = \left(\ket{0} + \ket{1}\right) / \sqrt{2}$
https://github.com/MicrosoftDocs/quantum-docs-pr.ja-JP/blob/live-sxs/articles/techniques/file-structure.md

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a3b73e69-99b5-c8a7-c20c-5b9b71f6c712
* Version Independent ID: 30736d0f-7226-ee59-7503-d0854104fac0
* Content: [Q# プログラムの概要 - Microsoft Quantum](https://docs.microsoft.com/ja-jp/quantum/techniques/file-structure?view=qsharp-preview)
* Content Source: [articles/techniques/file-structure.md](https://github.com/MicrosoftDocs/quantum-docs-pr.ja-JP/blob/live-sxs/articles/techniques/file-structure.md)
* Product: **quantum**
* GitHub Login: @QuantumWriter
* Microsoft Alias: **Christopher.Granade@microsoft.com**

**Comment by srvbpigh** [comment]
Hello, @tanaka-takayoshi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @tanaka-takayoshi 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team

**Comment by tanaka-takayoshi** [comment]
Hello @CeciAc 
Could you close the feedback form in "MT" document as far as you don't accept any feedback?
![image](https://user-images.githubusercontent.com/846156/81027775-e5940b00-8eb9-11ea-9477-43629a14f97c.png)

I know Microsoft feedback policy for Machine Translated document because I am a Microsoft MVP. However, everyone would consider we can put a feedback comment in the above form because we couldn't see the policy.
